apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template: # <--- THE POD STARTS HERE
    metadata:
      labels: # This label goes on the OUTSIDE of the Pod
        app: backend
    spec: # These are the rules for the Pod itself
      containers: # <--- THE CONTAINER STARTS HERE
      - name: backend
      # image: saikiran1412/backend:latest
        image:  "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env: # Environment variables are fed directly into the container
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/taskmanager"