{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- end }}